import java.sql.*;

/**
 * Created by £ukasz on 2015-11-03.
 */
public class MiastoManager {

    private Connection connection;

    private String url = "jdbc:hsqldb:hsql://localhost/workdb";

    private String createTablePerson = "CREATE TABLE Person(id bigint GENERATED BY DEFAULT AS IDENTITY, name varchar(20), yob integer)";

    private PreparedStatement addPersonStmt;
    private PreparedStatement deleteAllPersonsStmt;
    private PreparedStatement getAllPersonsStmt;

    private Statement statement;

    public MiastoManager()
    {
        try {
            connection = DriverManager.getConnection(url);
            statement = connection.createStatement();

            ResultSet rs = connection.getMetaData().getTables(null, null, null,
                    null);
            boolean tableExists = false;
            while (rs.next()) {
                if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
                    tableExists = true;
                    break;
                }
            }

            if (!tableExists)
                statement.executeUpdate(createTablePerson);

            addPersonStmt = connection
                    .prepareStatement("INSERT INTO Person (name, yob) VALUES (?, ?)");
            deleteAllPersonsStmt = connection
                    .prepareStatement("DELETE FROM Person");
            getAllPersonsStmt = connection
                    .prepareStatement("SELECT id, name, yob FROM Person");

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
